feeds:
  - name: srf
    url: https://www.srf.ch/news/bnf/rss/1890
  - name: nzz
    url: https://www.nzz.ch/recent.rss
  - name: 20min
    url: https://partner-feeds.beta.20min.ch/rss/20minuten/schweiz
  - name: tagesanzeiger
    url: https://partner-feeds.publishing.tamedia.ch/rss/tagesanzeiger/schweiz
  - name: blick
    url: https://www.blick.ch/schweiz/rss.xml
  - name: aargauerzeitung
    url: https://www.aargauerzeitung.ch/schweiz.rss
  - name: letemps
    url: https://www.letemps.ch/suisse.rss          # Französisch
  - name: cdt
    url: https://www.cdt.ch/feed/svizzera             # Italienisch (Corriere del Ticino)
  - name: laregione
    url: https://media.laregione.ch/files/domains/laregione.ch/rss/rss_svizzera.xml  # Italienisch
